require("Projects.Roadworks.ElectricCharger.functions.background.newBackgroundAnimation")
require("Projects.Roadworks.ElectricCharger.functions.background.randomCoordinate")
require("Projects.Roadworks.ElectricCharger.functions.background.handleAnimationEnd")
require("Projects.Roadworks.ElectricCharger.functions.background.handleColorAnimations")
require("Projects.Roadworks.ElectricCharger.functions.background.newSegmentGoal")
require("Projects.Roadworks.ElectricCharger.functions.background.lerpCoordinate")
require("Projects.Roadworks.ElectricCharger.functions.background.bezierPoints")
require("Projects.Roadworks.ElectricCharger.functions.background.drawBezier")