    output.setNumber(1, steeringLeft)
    output.setNumber(2, steeringRight)
    output.setNumber(3, throttle)
    output.setNumber(4, brakes)
    output.setNumber(5, selectedGear)
    output.setNumber(6, spotlightTiltRight)
    output.setNumber(7, spotlightTiltLeft)
    output.setNumber(8, spotlightYawRight)
    output.setNumber(9, spotlightYawLeft)
    output.setNumber(10, driverDoorPivot)
    output.setNumber(11, passengerDoorPivot)
	output.setNumber(12, hoodPivot)
	output.setNumber(13, trunkPivot)

    output.setBool(1, brakeLight)
    output.setBool(2, tailight)
    output.setBool(3, reverseLight)
    output.setBool(4, spotlight)
    output.setBool(5, (BRSynctimeslot+4)%(60+1) > 29) -- blinking of blinkers
    output.setBool(6, selectedBlinker == blinkRight or selectedBlinker == blinkBoth)
    output.setBool(7, selectedBlinker == blinkLeft or selectedBlinker == blinkBoth)
    output.setBool(32, carOn)