-- [BRS] ------------------------------------------------ [[ BOOLEAN ]] -
g_scriptsOn         = input.getBool(c_gbScriptActive)
g_showUI            = input.getBool(c_gbBootedOn)
g_blindSpotLeft     = input.getBool(c_gbBlindspotLeft)
g_blindSpotRight    = input.getBool(c_gbBlindspotRight)
g_honking           = input.getBool(c_gbHonking)
g_charging          = input.getBool(c_gbCharging)
g_slipping          = input.getBool(c_gbSlipping)
g_collisionWarning  = input.getBool(c_gbCollision)
g_damaged           = input.getBool(c_gbDamaged)
g_sos               = input.getBool(c_gbSosActive)
g_leftBlinker       = input.getBool(c_gbBlinkerLeft)
g_rightBlinker      = input.getBool(c_gbBlinkerRight)
g_hazards           = input.getBool(c_gbHazards)
g_interiorLight     = input.getBool(c_gbInteriorLight)
g_lowBeams          = input.getBool(c_gbLowBeams)
g_highBeams         = input.getBool(c_gbHighBeams)
g_automaticLights   = input.getBool(c_gbAutomaticLights)
g_doorsLocked       = input.getBool(c_gbDoorsLocked)
g_doorsOpened       = input.getBool(c_gbDoorsOpened)
g_universalBlink    = input.getBool(c_gbUniversalBlink)

-- [BRS] ------------------------------------------------ [[ NUMERICAL ]] -
require("Functions.Physic_sensor.getInputs")

g_managerState      = input.getNumber(c_gnCurrentState)
g_lightSetting      = input.getNumber(c_gnLightSetting)
g_temperature       = input.getNumber(c_gnTemperature)
g_rain              = input.getNumber(c_gnRain)
g_humidity          = input.getNumber(c_gnHumidity)
g_gear              = input.getNumber(c_gnCurrentGear)
g_battery           = input.getNumber(c_gnBattery)
g_batteryUsage      = input.getNumber(c_gnBatteryUsage)
g_range             = input.getNumber(c_gnEstimatedRange)