-- [BRS] - [[ Information ]] --
-- `25/08/05`
-- ### Description
-- Holds the list of commands, per stages, supported by the Lua script holding this value.
-- Must be defined in onTick when equals to nil to ensure proper multiplayer synchronization.
-- ### Used for
-- Knowing all the commands that can be instantiated and sent to another controller.
-- Must begin with a SendNumber to broadcast an address.
-- Can have commands that awaits after inputs.
-- ### Held data
-- ```json
-- {
--      [-adr] = {
--          {function, {inputs, inputs...}, optionalFuncToCallOnFinish }
--      }
-- }
g_masterCommands = nil